export const COMBO_MILESTONE_INTERVAL = 3;
export const STORM_HIGH_THRESHOLD = 75;
export const ENERGY_PARTICLE_DURATION_MS = 800;
export const ENERGY_PARTICLES_PER_GROUP = 8;
export const CHELSEA_TIP_DISPLAY_MS = 5000;
export const SCORE_PER_CORRECT_MATCH = 10;
export const SCORE_PER_GROUP_COMPLETE = 50;
export const SCORE_PER_COMBO_STEP = 5;
